import { Role } from "../models/Role";

export const COMPOSITION_CAPABILITIES = [
    "frontline",
    "engage",
    "peel",
    "hardCrowdControl",
    "waveclear",
    "sustainedDamage",
] as const;

export type CompositionCapability = (typeof COMPOSITION_CAPABILITIES)[number];
export type CompositionCapabilityStrength = 0 | 0.25 | 0.5 | 0.75 | 1;
export type CompositionProfile = Record<
    CompositionCapability,
    CompositionCapabilityStrength
>;

type PartialCompositionProfile = Partial<CompositionProfile>;
type CompositionProfileDefinition = {
    base: PartialCompositionProfile;
    roles?: Partial<Record<Role, PartialCompositionProfile>>;
};

const EMPTY_PROFILE: CompositionProfile = {
    frontline: 0,
    engage: 0,
    peel: 0,
    hardCrowdControl: 0,
    waveclear: 0,
    sustainedDamage: 0,
};

// Keep this list aligned with Data Dragon. An entry means that the champion
// has been reviewed; omitted capabilities intentionally have a value of zero.
// 0.25 is situational/minor, 0.5 is secondary, 0.75 is reliable but not
// defining, and 1 means the champion consistently fulfills the capability.
const SUPPORTED_CHAMPION_IDS = [
    "Aatrox",
    "Ahri",
    "Akali",
    "Akshan",
    "Alistar",
    "Ambessa",
    "Amumu",
    "Anivia",
    "Annie",
    "Aphelios",
    "Ashe",
    "AurelionSol",
    "Aurora",
    "Azir",
    "Bard",
    "Belveth",
    "Blitzcrank",
    "Brand",
    "Braum",
    "Briar",
    "Caitlyn",
    "Camille",
    "Cassiopeia",
    "Chogath",
    "Corki",
    "Darius",
    "Diana",
    "DrMundo",
    "Draven",
    "Ekko",
    "Elise",
    "Evelynn",
    "Ezreal",
    "Fiddlesticks",
    "Fiora",
    "Fizz",
    "Galio",
    "Gangplank",
    "Garen",
    "Gnar",
    "Gragas",
    "Graves",
    "Gwen",
    "Hecarim",
    "Heimerdinger",
    "Hwei",
    "Illaoi",
    "Irelia",
    "Ivern",
    "Janna",
    "JarvanIV",
    "Jax",
    "Jayce",
    "Jhin",
    "Jinx",
    "KSante",
    "Kaisa",
    "Kalista",
    "Karma",
    "Karthus",
    "Kassadin",
    "Katarina",
    "Kayle",
    "Kayn",
    "Kennen",
    "Khazix",
    "Kindred",
    "Kled",
    "KogMaw",
    "Leblanc",
    "LeeSin",
    "Leona",
    "Lillia",
    "Lissandra",
    "Locke",
    "Lucian",
    "Lulu",
    "Lux",
    "Malphite",
    "Malzahar",
    "Maokai",
    "MasterYi",
    "Mel",
    "Milio",
    "MissFortune",
    "MonkeyKing",
    "Mordekaiser",
    "Morgana",
    "Naafiri",
    "Nami",
    "Nasus",
    "Nautilus",
    "Neeko",
    "Nidalee",
    "Nilah",
    "Nocturne",
    "Nunu",
    "Olaf",
    "Orianna",
    "Ornn",
    "Pantheon",
    "Poppy",
    "Pyke",
    "Qiyana",
    "Quinn",
    "Rakan",
    "Rammus",
    "RekSai",
    "Rell",
    "Renata",
    "Renekton",
    "Rengar",
    "Riven",
    "Rumble",
    "Ryze",
    "Samira",
    "Sejuani",
    "Senna",
    "Seraphine",
    "Sett",
    "Shaco",
    "Shen",
    "Shyvana",
    "Singed",
    "Sion",
    "Sivir",
    "Skarner",
    "Smolder",
    "Sona",
    "Soraka",
    "Swain",
    "Sylas",
    "Syndra",
    "TahmKench",
    "Taliyah",
    "Talon",
    "Taric",
    "Teemo",
    "Thresh",
    "Tristana",
    "Trundle",
    "Tryndamere",
    "TwistedFate",
    "Twitch",
    "Udyr",
    "Urgot",
    "Varus",
    "Vayne",
    "Veigar",
    "Velkoz",
    "Vex",
    "Vi",
    "Viego",
    "Viktor",
    "Vladimir",
    "Volibear",
    "Warwick",
    "Xayah",
    "Xerath",
    "XinZhao",
    "Yasuo",
    "Yone",
    "Yorick",
    "Yunara",
    "Yuumi",
    "Zaahen",
    "Zac",
    "Zed",
    "Zeri",
    "Ziggs",
    "Zilean",
    "Zoe",
    "Zyra",
] as const;

const definitions = Object.fromEntries(
    SUPPORTED_CHAMPION_IDS.map((championId) => [
        championId,
        { base: {} } satisfies CompositionProfileDefinition,
    ]),
) as Record<string, CompositionProfileDefinition>;

function setCapability(
    capability: CompositionCapability,
    strength: CompositionCapabilityStrength,
    championIds: string[],
) {
    for (const championId of championIds) {
        definitions[championId].base[capability] = strength;
    }
}

// Secondary or build-dependent frontliners.
setCapability("frontline", 0.5, [
    "Aatrox",
    "Ambessa",
    "Briar",
    "Camille",
    "Darius",
    "Galio",
    "Garen",
    "Gnar",
    "Gragas",
    "Hecarim",
    "Illaoi",
    "JarvanIV",
    "Jax",
    "Kled",
    "LeeSin",
    "MonkeyKing",
    "Mordekaiser",
    "Nasus",
    "Olaf",
    "Rakan",
    "RekSai",
    "Renekton",
    "Sett",
    "Singed",
    "Swain",
    "Taric",
    "Trundle",
    "Udyr",
    "Urgot",
    "Vi",
    "Volibear",
    "Warwick",
    "XinZhao",
    "Yorick",
    "Zaahen",
]);
setCapability("frontline", 1, [
    "Alistar",
    "Amumu",
    "Braum",
    "Chogath",
    "DrMundo",
    "KSante",
    "Leona",
    "Malphite",
    "Maokai",
    "Nautilus",
    "Nunu",
    "Ornn",
    "Poppy",
    "Rammus",
    "Rell",
    "Sejuani",
    "Shen",
    "Sion",
    "Skarner",
    "TahmKench",
    "Zac",
]);

setCapability("engage", 0.5, [
    "Ahri",
    "Annie",
    "Ashe",
    "Bard",
    "Blitzcrank",
    "Briar",
    "Camille",
    "Diana",
    "Elise",
    "Galio",
    "Gnar",
    "Gragas",
    "Jhin",
    "Kled",
    "LeeSin",
    "Lissandra",
    "Zaahen",
    "Lux",
    "Morgana",
    "Nami",
    "Neeko",
    "Nocturne",
    "Nunu",
    "Pantheon",
    "Poppy",
    "Pyke",
    "RekSai",
    "Renata",
    "Rumble",
    "Sett",
    "Sion",
    "Syndra",
    "Taliyah",
    "Thresh",
    "TwistedFate",
    "Vex",
    "XinZhao",
    "Zyra",
]);
setCapability("engage", 1, [
    "Alistar",
    "Amumu",
    "Fiddlesticks",
    "Hecarim",
    "JarvanIV",
    "Kennen",
    "Leona",
    "Malphite",
    "Maokai",
    "Nautilus",
    "Ornn",
    "Rakan",
    "Rell",
    "Sejuani",
    "Skarner",
    "Vi",
    "MonkeyKing",
    "Zac",
]);

setCapability("peel", 0.5, [
    "Anivia",
    "Annie",
    "Ashe",
    "Bard",
    "Galio",
    "Gragas",
    "Ivern",
    "Karma",
    "Leona",
    "Lux",
    "Maokai",
    "Morgana",
    "Nautilus",
    "Neeko",
    "Orianna",
    "Ornn",
    "Senna",
    "Seraphine",
    "Shen",
    "Sona",
    "Soraka",
    "Syndra",
    "Taliyah",
    "Thresh",
    "Veigar",
    "Velkoz",
    "Zilean",
    "Zyra",
]);
setCapability("peel", 1, [
    "Alistar",
    "Braum",
    "Janna",
    "Lulu",
    "Milio",
    "Nami",
    "Poppy",
    "Renata",
    "TahmKench",
    "Taric",
    "Yuumi",
]);

setCapability("hardCrowdControl", 0.5, [
    "Aatrox",
    "Ahri",
    "Annie",
    "Ashe",
    "AurelionSol",
    "Bard",
    "Blitzcrank",
    "Briar",
    "Camille",
    "Chogath",
    "Darius",
    "Elise",
    "Fiddlesticks",
    "Fizz",
    "Gnar",
    "Gragas",
    "Hecarim",
    "Hwei",
    "Ivern",
    "Janna",
    "Jhin",
    "KSante",
    "Kennen",
    "Kled",
    "LeeSin",
    "Lillia",
    "Lissandra",
    "Lulu",
    "Lux",
    "Malphite",
    "Malzahar",
    "Milio",
    "Morgana",
    "Nami",
    "Neeko",
    "Nocturne",
    "Nunu",
    "Ornn",
    "Pantheon",
    "Poppy",
    "Pyke",
    "Qiyana",
    "Rakan",
    "Rammus",
    "RekSai",
    "Renata",
    "Riven",
    "Sejuani",
    "Senna",
    "Seraphine",
    "Sett",
    "Shen",
    "Singed",
    "Sion",
    "Swain",
    "Syndra",
    "TahmKench",
    "Taliyah",
    "Taric",
    "Thresh",
    "Trundle",
    "TwistedFate",
    "Udyr",
    "Urgot",
    "Varus",
    "Vex",
    "Vi",
    "Volibear",
    "Warwick",
    "XinZhao",
    "Yone",
    "Zaahen",
    "Zac",
    "Zilean",
    "Zoe",
    "Zyra",
]);
setCapability("hardCrowdControl", 1, [
    "Alistar",
    "Amumu",
    "Anivia",
    "Braum",
    "Galio",
    "JarvanIV",
    "Leona",
    "Maokai",
    "Nautilus",
    "Rell",
    "Sejuani",
    "Skarner",
]);

setCapability("waveclear", 0.5, [
    "Aatrox",
    "Ahri",
    "Akali",
    "Akshan",
    "Ambessa",
    "Annie",
    "Aphelios",
    "Ashe",
    "Aurora",
    "Briar",
    "Caitlyn",
    "Camille",
    "Chogath",
    "Corki",
    "Darius",
    "Diana",
    "Draven",
    "Ekko",
    "Ezreal",
    "Fiddlesticks",
    "Fiora",
    "Fizz",
    "Galio",
    "Garen",
    "Gnar",
    "Gragas",
    "Graves",
    "Gwen",
    "Hecarim",
    "Illaoi",
    "Irelia",
    "JarvanIV",
    "Jax",
    "Jayce",
    "Jhin",
    "Kaisa",
    "Kalista",
    "Karma",
    "Kassadin",
    "Katarina",
    "Kayn",
    "Kennen",
    "Kindred",
    "Kled",
    "Leblanc",
    "LeeSin",
    "Lissandra",
    "Locke",
    "Lucian",
    "Malphite",
    "Mel",
    "MissFortune",
    "MonkeyKing",
    "Mordekaiser",
    "Naafiri",
    "Nasus",
    "Neeko",
    "Nilah",
    "Nocturne",
    "Nunu",
    "Olaf",
    "Ornn",
    "Pantheon",
    "Poppy",
    "Qiyana",
    "Renekton",
    "Rengar",
    "Riven",
    "Rumble",
    "Samira",
    "Sett",
    "Shen",
    "Shyvana",
    "Singed",
    "Skarner",
    "Smolder",
    "Swain",
    "Sylas",
    "TahmKench",
    "Talon",
    "Teemo",
    "Tristana",
    "Trundle",
    "Tryndamere",
    "Twitch",
    "Udyr",
    "Urgot",
    "Varus",
    "Vayne",
    "Vex",
    "Vi",
    "Viego",
    "Vladimir",
    "Volibear",
    "Warwick",
    "Xayah",
    "XinZhao",
    "Yasuo",
    "Yone",
    "Yorick",
    "Yunara",
    "Zaahen",
    "Zed",
    "Zeri",
    "Zoe",
]);
setCapability("waveclear", 1, [
    "Anivia",
    "AurelionSol",
    "Azir",
    "Brand",
    "Cassiopeia",
    "Gangplank",
    "Heimerdinger",
    "Hwei",
    "Jinx",
    "Karthus",
    "Kayle",
    "KogMaw",
    "Lux",
    "Malzahar",
    "Orianna",
    "Ryze",
    "Seraphine",
    "Sion",
    "Sivir",
    "Syndra",
    "Taliyah",
    "Veigar",
    "Velkoz",
    "Viktor",
    "Xerath",
    "Ziggs",
    "Zyra",
]);

// Refine the broad secondary/primary groups into a five-level gradient.
setCapability("frontline", 0.25, [
    "Ambessa",
    "Camille",
    "Hecarim",
    "LeeSin",
    "Rakan",
    "RekSai",
    "Vi",
    "XinZhao",
]);
setCapability("frontline", 0.75, [
    "Galio",
    "Gragas",
    "JarvanIV",
    "Sett",
    "Swain",
    "Taric",
    "Udyr",
    "Volibear",
]);

setCapability("engage", 0.25, [
    "Ahri",
    "Annie",
    "Elise",
    "Jhin",
    "Lux",
    "Morgana",
    "Syndra",
    "TwistedFate",
    "Zyra",
]);
setCapability("engage", 0.75, [
    "Ashe",
    "Galio",
    "Gnar",
    "Gragas",
    "Nunu",
    "Poppy",
    "Renata",
    "Sett",
    "Sion",
]);

setCapability("peel", 0.25, [
    "Annie",
    "Ashe",
    "Bard",
    "Galio",
    "Gragas",
    "Leona",
    "Lux",
    "Maokai",
    "Nautilus",
    "Neeko",
    "Orianna",
    "Syndra",
    "Taliyah",
    "Veigar",
    "Velkoz",
    "Zyra",
]);
setCapability("peel", 0.75, [
    "Ivern",
    "Karma",
    "Morgana",
    "Senna",
    "Seraphine",
    "Shen",
    "Sona",
    "Soraka",
    "Thresh",
    "Zilean",
]);

setCapability("hardCrowdControl", 0.25, [
    "Aatrox",
    "Briar",
    "Camille",
    "Darius",
    "Fizz",
    "Ivern",
    "Jhin",
    "KSante",
    "LeeSin",
    "Senna",
    "Singed",
    "Trundle",
    "Urgot",
    "Yone",
]);
setCapability("hardCrowdControl", 0.75, [
    "Anivia",
    "Ashe",
    "Bard",
    "Chogath",
    "Fiddlesticks",
    "Galio",
    "Gragas",
    "Lissandra",
    "Maokai",
    "Ornn",
    "Poppy",
    "Rakan",
    "Rammus",
    "Sejuani",
    "Sion",
    "Taliyah",
    "Thresh",
    "Vex",
    "Zac",
]);

setCapability("waveclear", 0.25, [
    "Aatrox",
    "Akali",
    "Camille",
    "Draven",
    "Fiora",
    "Fizz",
    "Jhin",
    "Kled",
    "Leblanc",
    "LeeSin",
    "Nunu",
    "Poppy",
    "Rengar",
    "Shen",
    "TahmKench",
    "Vayne",
    "Warwick",
    "XinZhao",
]);
setCapability("waveclear", 0.75, [
    "Ahri",
    "Annie",
    "Aphelios",
    "Aurora",
    "Caitlyn",
    "Corki",
    "Diana",
    "Garen",
    "Gnar",
    "Graves",
    "Gwen",
    "Irelia",
    "Kaisa",
    "Karma",
    "Kennen",
    "Lissandra",
    "Lucian",
    "Mel",
    "MissFortune",
    "Neeko",
    "Rumble",
    "Samira",
    "Smolder",
    "Swain",
    "Tristana",
    "Twitch",
    "Varus",
    "Vex",
    "Xayah",
    "Yone",
    "Zeri",
    "Zoe",
]);

setCapability("sustainedDamage", 0.25, [
    "Ahri",
    "Akali",
    "Akshan",
    "Ambessa",
    "Annie",
    "Aurora",
    "Diana",
    "Ekko",
    "Elise",
    "Ezreal",
    "Fiddlesticks",
    "Fizz",
    "Hwei",
    "Jayce",
    "Jhin",
    "Kassadin",
    "Katarina",
    "Kled",
    "Leblanc",
    "Locke",
    "Lux",
    "Malzahar",
    "Mel",
    "Naafiri",
    "Neeko",
    "Nidalee",
    "Nocturne",
    "Orianna",
    "Pantheon",
    "Qiyana",
    "Rengar",
    "Senna",
    "Syndra",
    "Talon",
    "TwistedFate",
    "Veigar",
    "Vex",
    "Xerath",
    "Zed",
    "Ziggs",
    "Zoe",
    "Zyra",
]);
setCapability("sustainedDamage", 0.5, [
    "Aatrox",
    "Anivia",
    "Brand",
    "Briar",
    "Camille",
    "Gangplank",
    "Garen",
    "Gnar",
    "Gragas",
    "Hecarim",
    "Illaoi",
    "Kayn",
    "Kennen",
    "Lillia",
    "MissFortune",
    "MonkeyKing",
    "Nasus",
    "Renekton",
    "Riven",
    "Rumble",
    "Sett",
    "Singed",
    "Sylas",
    "Taliyah",
    "Teemo",
    "Velkoz",
]);
setCapability("sustainedDamage", 0.75, [
    "Ashe",
    "AurelionSol",
    "Caitlyn",
    "Corki",
    "Darius",
    "Draven",
    "Graves",
    "Heimerdinger",
    "Irelia",
    "Lucian",
    "Mordekaiser",
    "Olaf",
    "Samira",
    "Shyvana",
    "Swain",
    "Udyr",
    "Urgot",
    "Varus",
    "Viktor",
    "Vladimir",
    "Volibear",
    "Warwick",
    "XinZhao",
    "Yorick",
    "Zaahen",
]);
setCapability("sustainedDamage", 1, [
    "Aphelios",
    "Azir",
    "Belveth",
    "Cassiopeia",
    "Fiora",
    "Gwen",
    "Jax",
    "Jinx",
    "Kaisa",
    "Kalista",
    "Karthus",
    "Kayle",
    "Kindred",
    "KogMaw",
    "MasterYi",
    "Nilah",
    "Ryze",
    "Sivir",
    "Smolder",
    "Tristana",
    "Trundle",
    "Tryndamere",
    "Twitch",
    "Vayne",
    "Viego",
    "Xayah",
    "Yasuo",
    "Yone",
    "Yunara",
    "Zeri",
]);

// Standard builds can change a capability materially by role.
definitions.Galio.roles = {
    [Role.Middle]: {
        frontline: 0.5,
        peel: 0.5,
        waveclear: 0.75,
        sustainedDamage: 0.25,
    },
    [Role.Support]: {
        frontline: 1,
        peel: 1,
        waveclear: 0.25,
        sustainedDamage: 0.25,
    },
};
definitions.Karma.roles = {
    [Role.Middle]: { peel: 0.5, waveclear: 0.75, sustainedDamage: 0.25 },
    [Role.Support]: { peel: 0.75, waveclear: 0.5, sustainedDamage: 0 },
};
definitions.Maokai.roles = {
    [Role.Support]: {
        frontline: 0.75,
        waveclear: 0.25,
        sustainedDamage: 0,
    },
};
definitions.Seraphine.roles = {
    [Role.Bottom]: { peel: 0.5, waveclear: 1, sustainedDamage: 0.5 },
    [Role.Middle]: { peel: 0.5, waveclear: 1, sustainedDamage: 0.5 },
    [Role.Support]: { peel: 0.75, waveclear: 0.5, sustainedDamage: 0.25 },
};
definitions.Senna.roles = {
    [Role.Bottom]: { peel: 0.5, sustainedDamage: 0.75 },
    [Role.Support]: { peel: 0.75, sustainedDamage: 0.5 },
};
definitions.Gragas.roles = {
    [Role.Top]: { frontline: 0.75, waveclear: 0.5, sustainedDamage: 0.5 },
    [Role.Jungle]: {
        frontline: 0.75,
        waveclear: 0.5,
        sustainedDamage: 0.5,
    },
    [Role.Middle]: {
        frontline: 0.25,
        waveclear: 0.75,
        sustainedDamage: 0.25,
    },
    [Role.Support]: {
        frontline: 0.5,
        waveclear: 0.25,
        sustainedDamage: 0.25,
    },
};
definitions.Poppy.roles = {
    [Role.Top]: { frontline: 1, waveclear: 0.5, sustainedDamage: 0.5 },
    [Role.Jungle]: { frontline: 1, waveclear: 0.5, sustainedDamage: 0.5 },
    [Role.Support]: {
        frontline: 0.75,
        waveclear: 0.25,
        sustainedDamage: 0.25,
    },
};
definitions.Malphite.roles = {
    [Role.Top]: { frontline: 1, waveclear: 0.75, sustainedDamage: 0.25 },
    [Role.Middle]: {
        frontline: 0.5,
        waveclear: 0.75,
        sustainedDamage: 0.25,
    },
    [Role.Support]: { frontline: 0.75, waveclear: 0.25, sustainedDamage: 0 },
};
definitions.Swain.roles = {
    [Role.Middle]: {
        frontline: 0.75,
        waveclear: 0.75,
        sustainedDamage: 0.75,
    },
    [Role.Bottom]: {
        frontline: 0.75,
        waveclear: 0.75,
        sustainedDamage: 0.75,
    },
    [Role.Support]: {
        frontline: 0.5,
        waveclear: 0.25,
        sustainedDamage: 0.5,
    },
};
definitions.TahmKench.roles = {
    [Role.Top]: { peel: 0.5, waveclear: 0.5, sustainedDamage: 0.5 },
    [Role.Support]: { peel: 1, waveclear: 0.25, sustainedDamage: 0.25 },
};
definitions.Lux.roles = {
    [Role.Middle]: { peel: 0.25, waveclear: 1, sustainedDamage: 0.25 },
    [Role.Support]: { peel: 0.5, waveclear: 0.5, sustainedDamage: 0.25 },
};
definitions.Brand.roles = {
    [Role.Middle]: { waveclear: 1, sustainedDamage: 0.75 },
    [Role.Bottom]: { waveclear: 1, sustainedDamage: 0.75 },
    [Role.Jungle]: { waveclear: 0.5, sustainedDamage: 0.75 },
    [Role.Support]: { waveclear: 0.5, sustainedDamage: 0.5 },
};

export function getCompositionProfile(championId: string, role: Role) {
    const definition = definitions[championId];
    if (!definition) return undefined;

    return {
        ...EMPTY_PROFILE,
        ...definition.base,
        ...definition.roles?.[role],
    } satisfies CompositionProfile;
}

export function getMissingCompositionProfileIds(championIds: string[]) {
    return championIds.filter((championId) => !definitions[championId]);
}
